site_name: Jupyter的个人网站
theme:
  name: material
nav:
  - 讲稿:
    - LECTURE/index.md 
    - Linux:
      - Linux讲座: LECTURE/Linux/linux.md
      - 命令行入门精简版: LECTURE/Linux/commands-concise.md
    - Markdown:
      - Markdown讲座: LECTURE/Markdown/markdown.md
      - VSCode及插件安装: LECTURE/Markdown/vscode-extension.md
    - Git:
      - Git: LECTURE/Git/git.md
      - Git例子: LECTURE/Git/git-demos.md
      - Git合作: LECTURE/Git/git-teamwork.md
      - Windows安装Git: LECTURE/Git/windows-install.md
    - 应用开发设计: LECTURE/App/app-design.md
    - 在macOS上用VSCode写C++代码:
      - 0 介绍: LECTURE/vscode-cpp/0_about.md
      - 1 前言和课程说明: LECTURE/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: LECTURE/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: LECTURE/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: LECTURE/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: LECTURE/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: LECTURE/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: LECTURE/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: LECTURE/vscode-cpp/8_课程回顾.md
      - 其他: LECTURE/vscode-cpp/9_others.md
      - 极速版: LECTURE/vscode-cpp/10_极速版.md
      - 补充: LECTURE/vscode-cpp/11_补充.md
    - 英语音标教学: LECTURE/English/phonetic-symbol.md
    - 魔方:
      - LECTURE/Cube/basic.md
  - 博客:
    - BLOG/index.md
    - BLOG/others.md
    - Apple:
      - BLOG/Apple/mac-recommend.md
      - BLOG/Apple/ipad-recommend.md
    - macOS:
      - BLOG/macOS/tree.md
      - BLOG/macOS/zoom.md
      - BLOG/macOS/sharing-mac-android.md
      - BLOG/macOS/mad.md
      - BLOG/macOS/stream.md
      - BLOG/macOS/intel-windows.md
    - Markdown:
      - BLOG/Markdown/grammars.md
      - BLOG/Markdown/mkdocs-site.md
      - BLOG/Markdown/mdbook-site.md
      - BLOG/Markdown/github-pages.md
    - Linux:
      - BLOG/Linux/vim.md
      - BLOG/Linux/tmux.md
      - BLOG/Linux/unix.md
      - BLOG/Linux/kernel-compile.md
      - BLOG/Linux/pi-start.md
    - OS:
      - BLOG/OS/fork-exec-spawn.md
      - BLOG/OS/fork-example.md
    - 计算机网络:
      - BLOG/Network/learning.md
      - BLOG/Network/nouns.md
    